"""
Jarvis Platform
Stage-135.0 — Governance Strategic Decision Intelligence Engine

Purpose
-------
Evaluate and rank simulated governance stabilization strategies
to produce a deterministic advisory decision.

Consumes simulation outputs generated by Stage-134 and selects
the strategy with the highest predicted stability improvement.

Key Guarantees
--------------
• Deterministic strategy ranking
• Read-only simulation input
• Append-only ledger reporting
• No execution authority
• No mutation authority
"""

import hashlib
import json
import time
from typing import Dict, Any, List


class GovernanceStrategicDecisionIntelligenceEngine:

    MODULE = "governance_strategic_decision_intelligence_engine"
    STAGE = "135.0"

    def __init__(self, ledger):
        self.ledger = ledger

    # ---------------------------------------------------------

    def _hash(self, payload: Dict[str, Any]) -> str:
        encoded = json.dumps(payload, sort_keys=True).encode()
        return hashlib.sha256(encoded).hexdigest()

    # ---------------------------------------------------------

    def _score_strategy(self, base_score: float, simulated_score: float) -> float:
        """
        Deterministic improvement scoring.
        """
        improvement = simulated_score - base_score
        return round(improvement, 6)

    # ---------------------------------------------------------

    def decide(
        self,
        base_fusion_score: float,
        simulated_strategies: List[Dict[str, Any]]
    ) -> Dict[str, Any]:

        ranked: List[Dict[str, Any]] = []

        for strategy in simulated_strategies:

            simulated_score = strategy["simulated_fusion_score"]

            score = self._score_strategy(base_fusion_score, simulated_score)

            ranked.append({
                "strategy": strategy["strategy"],
                "simulated_fusion_score": simulated_score,
                "improvement_score": score
            })

        ranked.sort(key=lambda x: x["improvement_score"], reverse=True)

        best_strategy = ranked[0] if ranked else None

        report = {
            "module": self.MODULE,
            "stage": self.STAGE,
            "timestamp": int(time.time()),
            "base_fusion_score": base_fusion_score,
            "ranked_strategies": ranked,
            "recommended_strategy": best_strategy
        }

        report["hash"] = self._hash(report)

        self.ledger.append(report)

        return report